Gestao_Ouvidoria/Controllers/ManifestacaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestao_Ouvidoria.Models;

namespace Gestao_Ouvidoria.Controllers
{
    public class ManifestacaoController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        // GET: Manifestacao
        public ActionResult Index()
        {
            var manifestacoes = db.Manifestacao.Include(m => m.Perfil);
            ViewBag.Respondida = db.Manifestacao.Where(a => a.Status == TipoStatus.Respondida).ToList().Count;
            ViewBag.Vencida = db.Manifestacao.Where(a => a.Status == TipoStatus.Vencida).ToList().Count;
            ViewBag.Pendente = db.Manifestacao.Where(a => a.Status == TipoStatus.Pendente).ToList().Count;
            ViewBag.Excluida = db.Manifestacao.Where(a => a.Status == TipoStatus.Excluida).ToList().Count;
            ViewBag.Total = db.Manifestacao.ToList().Count;
            return View(manifestacoes.ToList());
        }


        // GET: Manifestacao/Create
        public ActionResult Create()
        {
            ViewBag.IdPerfil = new SelectList(db.Perfil, "Id", "Nome");
            return View();
        }

        // POST: Manifestacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Campus,Curso,TipoSolicitacao,Setor,Assunto,ManifestacaoConteudo,IdPerfil")] Manifestacao manifestacao)
        {
            if (ModelState.IsValid)
            {
                manifestacao.Created = DateTime.Now;
                manifestacao.Modified = DateTime.Now;
                manifestacao.Status = TipoStatus.Pendente;
                manifestacao.StatusSetor = TipoStatusSetor.NaoEncaminhado;
                db.Manifestacao.Add(manifestacao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdPerfil = new SelectList(db.Perfil, "Id", "Nome", manifestacao.IdPerfil);
            return View(manifestacao);
        }


        // GET: Manifestacao/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manifestacao manifestacao = db.Manifestacao.Find(id);
            if (manifestacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.ButtonDisabled = (manifestacao.Status == TipoStatus.Respondida || manifestacao.StatusSetor == TipoStatusSetor.Encaminhado);
            return View(manifestacao);
        }

        // POST: Manifestacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Manifestacao manifestacao = db.Manifestacao.Find(id);
            manifestacao.Status = TipoStatus.Excluida;
            db.Entry(manifestacao).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestao_Ouvidoria/Controllers/RespostaManifestacaoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Gestao_Ouvidoria.Helpers;
using Gestao_Ouvidoria.Models;

namespace Gestao_Ouvidoria.Controllers
{
    public class RespostaManifestacaoController : Controller
    {
        private OuvidoriaContext db = new OuvidoriaContext();

        // GET: RespostaManifestacao
        public ActionResult Index()
        {
            var respostaManifestacao = db.RespostaManifestacao.Include(r => r.Manifestacao);
            return View(respostaManifestacao.ToList());
        }

        // GET: RespostaManifestacao/Create/5
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manifestacao manifestacao = db.Manifestacao.Find(id);
            ViewBag.Manifestacao = manifestacao;

            if (manifestacao == null)
            {
                return HttpNotFound();
            }

            ViewBag.FormDisabled = (manifestacao.Status != TipoStatus.Pendente);
            ViewBag.IdManifestacao = new SelectList(db.Manifestacao, "Id", "Assunto", id);
            List<Setor> setores = Enum.GetValues(typeof(Setor)).Cast<Setor>().ToList();
            ViewBag.setores = new SelectList(setores);

            return View();
        }


        // POST: RespostaManifestacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RespostaManifestacao respostaManifestacao, HttpPostedFileBase file)
        {
            Manifestacao manifestacao = db.Manifestacao.Find(respostaManifestacao.IdManifestacao);
            ViewBag.Manifestacao = manifestacao;
            ViewBag.IdManifestacao = new SelectList(db.Manifestacao, "Id", "Assunto", respostaManifestacao.IdManifestacao);
          

            if (ModelState.IsValid)
            {

                if (file.ContentLength > 0)
                {
                    try
                    {
                        string folder = "~/Arquivo/"+manifestacao.Id.ToString();
                        Directory.CreateDirectory(Server.MapPath(folder));
                        string pathFile = Path.Combine(Server.MapPath(folder),
                           Path.GetFileName(file.FileName));
                        
                        respostaManifestacao.Arquivo = pathFile;
                        file.SaveAs(pathFile);

                        ViewBag.Message = "Your message for success";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                

                manifestacao.Status = TipoStatus.Respondida;
                db.Entry(manifestacao).State = EntityState.Modified;
                db.RespostaManifestacao.Add(respostaManifestacao);
                db.SaveChanges();

                return RedirectToAction("Encaminhar", new { id = manifestacao.Id });
            }

            return View(respostaManifestacao);
        }

        // GET: Manifestacao/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RespostaManifestacao respostaManifestacao = db.RespostaManifestacao.Find(id);
   
            if (respostaManifestacao == null)
            {
                return HttpNotFound();
            }
            return View(respostaManifestacao);
        }


        // GET: RespostaManifestacao/Encaminhar/5
        public ActionResult Encaminhar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
          
            Manifestacao manifestacao = db.Manifestacao.Find(id);
            ViewBag.Manifestacao = manifestacao;
            RespostaManifestacao respostaManifestacao = db.RespostaManifestacao.FirstOrDefault(e => e.IdManifestacao == manifestacao.Id);
            ViewBag.RespostaManifestacao = respostaManifestacao;


            List<Setor> setores = Enum.GetValues(typeof(Setor)).Cast<Setor>().ToList();
            ViewBag.setores = new SelectList(setores);

            if (manifestacao == null)
            {
                return HttpNotFound();
            }

            return View();
        }

        // POST: RespostaManifestacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Encaminhar(Manifestacao manifestacao)
        {
            Manifestacao manifestacaoRow = db.Manifestacao.Find(manifestacao.Id);
            ViewBag.Manifestacao = manifestacaoRow;
            RespostaManifestacao respostaManifestacao = db.RespostaManifestacao.FirstOrDefault(e => e.IdManifestacao == manifestacao.Id);
            ViewBag.RespostaManifestacao = respostaManifestacao;

            manifestacaoRow.StatusSetor = TipoStatusSetor.Encaminhado;
            db.Entry(manifestacaoRow).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestao_Ouvidoria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="https://cdn.datatables.net/v/bs-3.3.7/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-html5-1.3.1/b-print-1.3.1/datatables.min.css" rel="stylesheet" />




    @Styles.Render("~/Content/datatablecss")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Portal UGB", "Index", "Manifestacao", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Manifestacao", new { area = "" }, new { @class = "linknavbar" })</li>
                    <li>@Html.ActionLink("Manifestações Respondidas", "Index", "RespostaManifestacao", new { area = "" }, new { @class = "linknavbar" })</li>
                    <li>@Html.ActionLink("Perfil", "Index", "Perfil", new { area = "" }, new { @class = "linknavbar" })</li>

                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatablejs")
    @RenderSection("scripts", required: false)
</body>
</html>